wolfSSL/wolfBoot

Makefile
=> Minor makefile fix partition offset during build

Makefile, arch.mk, docs/Targets.md, docs/compile.md, hal/stm32f7.c, hal/stm32f7.ld, include/hal.h, src/boot_arm.c, src/loader.c, test-app/ARM-stm32f7.ld, test-app/Makefile, test-app/app_stm32f7.c, test-app/system.c
This PR adds support for dual-bank devices with hardware-assisted bank swap.
It also includes a HAL and test application for STM32F7.
Dual-bank HW-assisted swap is supported by STM32F76x and STM32F77x, as specified in STMicroelectronics "AN4826: STM32F7 Series Flash memory dual bank mode".
=> Added support for STM32F7 + DUALBANK_SWAP hw-assisted support

include/wolfboot/wolfboot.h, src/image.c, src/libwolfboot.c, src/loader.c
Fixes to recognize update_type when the update resides on external memory (e.g. SPI flash).
=> Wolfboot self-update fix

Makefile
Added missing CFLAGS to group unused symbols.
wolfBoot binary size is consistently reduced.
Updating benchmark figures accordingly.
=> Added -ffunction-sections -fdata-sections to CFLAGS to group unused symbols

arch.mk
According to Jenkins, two test cases (101 & 111) are still failing, because linking RSA+SHA3 excludes sha256 and results in missing symbols at linking time. sha256 can be included in all cases and discarded automatically when not needed.
=> Link sha256.o module even if sha3 is selected, as it's needed by RSA

IDE/XilinxSDK/README.md, IDE/XilinxSDK/boot.bif, IDE/XilinxSDK/boot_auth.bif, docs/HAL.md, hal/zynq.c, hal/zynq.ld, src/image.c, src/libwolfboot.c, src/loader.c, src/update_flash.c, tools/keytools/sign.c
* Fix for C signing tool and SHA3 padding at 8-bytes.
* Fix for Zynqmp tap delay and non EL-3 use of cpufreq.
* Fix for cast warnings to `ext_flash_*` API's.
* Updated Xilinx SDK instructions for EL-1 / Hypervisor support.
* Updated the `zynq.ld` script to use 0x4000000 and only DDR0 region.
* Updated the example BIF files to use EL-1 for wolfBoot.
=> Fixes for Zynqmp with BL31 and C signing tool padding

tools/keytools/sign.c
Ed25519 sign failed with the native C tool. Private key import returned -132. Replaced with full key import/manual set of pubkey buffer.
=> Fix importing Ed25519 key in C sign tool

tools/keytools/keygen.c
Fix for keygen.c (ed25519 key):
Ed25519.der should contain the full key (both private + public halves).
=> Fixed bug in keygen.c append missing public key to ed25519.der

tools/keytools/keygen.c, tools/keytools/sign.c, tools/keytools/sign.py
When a public key argument is expected by the `sign` tools, the parse size should be adjusted accordingly, i.e. 32 bytes for ed25519, 64 bytes for ECC256.
=> Keytools fix pubkey parser

src/update_flash.c
invert logic if/while to avoid truncated bootloader when copying from external flash into multiple sectors.
Thanks to Liam Oorts for the bug report.
=> Fixed loop logic in bootloader update

tools/test.mk
TPM pin must be floating only if target is controlling it (TPM tests). 
In all other tests, the TPM CS must be controlled by the bench and set to 1.
This patch enforces TPM_CS=1 on testbed on/off, and provide tpm-mute/unmute targets used during non-regression tests with TPM controlled by the target.
=> [Jenkins] fixed SPI CS pin config on test-bench

hal/spi/spi_drv_nrf52.c, hal/spi/spi_drv_stm32.c, include/spi_drv.h, src/spi_flash.c
Added RAMFUNCTION tag to SPI flash functions in order to allow wolfBoot updates from SPI flash.
=> Allow bootloader update from SPI flash

hal/spi/spi_drv_nrf52.c, hal/spi/spi_drv_stm32.c, include/spi_drv.h, src/spi_flash.c, src/update_flash.c
When the update image is valid, yet not marked for update, and the boot image is invalid/absent/corrupted, wolfBoot would try to run a forced last-resort update.
This mechanism has a logic flaw, which is fixed by this PR.
Existing tests on Jenkins are successful :heavy_check_mark:
=> Fix last-resort update

src/libwolfboot.c, tools/uart-flash-server/ufserver.c
Fixed bug in encrypted update.
See ZD 10601
=> Fixed bug in encrypted update, removed swap_counter.

src/libwolfboot.c, tools/scripts/prepare_encrypted_update.sh, tools/uart-flash-server/ufserver.c
- Encryption key slot moved to the end of the partition
- When encryption is enabled, partition flag and sector flags bitmap are moved back by `ENCRYPT_KEY_SIZE + ENCRYPT_NONCE_SIZE`
- Updated `uart_flash_server` to detect and support encrypted partitions
ZD 10733
=> Relocate encryption key slot to the end of the flash partition

src/libwolfboot.c
Since the encryption key + nonce has been relocated (#75), the encrypt/decrypt functions must take into account the sectors used for the flags bitmap.
See ZD 10882.
=> Fix bug in encryption - account for flags offset

hal/spi/spi_drv_stm32.c
Hi,
By removing this flag, we're setting the baudrate prescaler from fPCLK/64 to fPCLK/2. This results in faster transfer speeds to external flash. We've already tested this change on all of our instances for a longer time.
=> increase spi speed

include/wolfboot/wolfboot.h, src/libwolfboot.c, src/update_flash.c
When installing the update the encryption key should be kept until the update is marked as successful.
This patch ensures that the encryption key is restored in the right location after the update is installed, to allow the fallback mechanism to kick in if the update is not confirmed after the next boot.
The encryption key is dropped after a successful update.
Ref: ZD 11323
=> Fix fallback using encryption by storing the key after swapping

test-app/app_stm32h7.c
This wolfBoot application has been specifically developed for and tested on NUCLEO-H753ZI.
Toogle between application A and B to use the application code to test firmware update capability of wolfBoot and to distinguish the two application versions.
This application has specifically been developed to work with the newest HAL for STM32H7.
It features UART and LED setup.
Pull request as agreed with Daniele.
=> STM32H7 Test Application

Makefile, tools/test-enc.mk, tools/test.mk
Allow override of `WOLFBOOT_ROOT` to allow proper detection of the signing/keygen tools.
=> Support for overriding the wolfBoot root

.gitignore, hal/zynq.c
* Add support for using the Xilinx BSP QSPI driver. Enabled with `USE_XQSPIPSU`.
* Update to latest wolfSSL submodule (fixes Chacha build error in Visual Studio).
ZD 11361
=> Xilinx support for BSP QSPI driver

Makefile, arch.mk, include/wolfboot/wolfboot.h, src/image.c, test-app/Makefile, tools/bin-assemble/Makefile, tools/bin-assemble/bin-assemble.c, tools/test-expect-version/Makefile, tools/test-expect-version/test-expect-version.c, tools/test-update-server/Makefile, tools/test.mk
Add `bin-assemble` tool instead of `dd` for more flexible assembly of factory image.
Add Big Endian support for header and trailer
makefile clean up
* remove unused targets
* distclean - cleans all tools
* remove use of some temp files
=> make: PPC/Big Endian support

docs/firmware_update.md
Swap interruption recovery and general description of self-update
include that it can not be interrupted.
=> docs: Add info on swap interruption and self-update

tools/test.mk
removed accidental newline in the `test-all` recipe
=> Fixed test-all target

tools/keytools/sign.py
Same issue as [wolfcrypt-py/pulls/24](https://github.com/wolfSSL/wolfcrypt-py/pull/24)
The array slicing in `ecc.decode_key_raw()` call wrongly assumed array as
inclusive (i.e. [0:31] to include from 0 to 31, instead of the correct
form [0:32]).
=> Fixed key import ranges in ecc sign.py

hal/stm32l5.c, src/update_flash_hwswap.c, test-app/app_stm32l5.c
This patch fixes the dual-bank secure boot mode on STM32L5.
HW swap on this platform will reboot the system, so the status flag of the partition must be only updated after the swap (i.e. in the next reboot in this case, where the active partition is currently mapped as BOOT).
Changed the test app for stm32l5 to keep the boot led on when the version is >1.
=> Fix STM32L5 dual-bank mode

options.mk, src/xmalloc.c, tools/keytools/sign.py, tools/test.mk
- Added CI tests for Ed448
- Fixed `sign.py` signature len and manifest header size
- Added support for Ed448 with `WOLFBOOT_SMALL_STACK`, using fixed `xmalloc`
=> Added tests for ed448, fixed sign.py

src/delta.c, tools/test-delta.mk, tools/uart-flash-server/Makefile
- Fixed patch offset in delta update (ZD12933)
- uart-flash-server: build own libwolfboot.o (to avoid object mismatch when building after wolfBoot)
- Fixed test cases for delta updates
=> Delta update fixes

tools/test.mk
- Fixed regressions in test cases 34/44, due to a missing `make clean` in the test case before creating the new image.
- Added missing test cases (912, 1074) for Ed448
=> Added missing test cases for Ed448 + Fixed regressions in self test

hal/ti_hercules.c, src/boot_arm.c
- load `f021_lookup_bank()` into RAM
- `arch_reboot()` for TMS570
=> Fixes for Cortex R5 self-update

Makefile, arch.mk
ZD 13482
- Merging of #81 lost the `PSOC6_CRYPTO_OBJS` block: re-added.
- Sha512_Init_ex is now used internally by ed25519, so added a stub in the driver
- PSoC6 BSP included in all cases, not as part of `PKA_OBJS`
Tested with `cypsoc6.config`; `make` and `make SIGN=ECC256`.
=> Fixes to build PSOC6

options.mk, tools/keytools/sign.c, tools/keytools/sign.py
ZD 12933
Manifest header 'extra' fields must be word-aligned. The python `sign` tool now adds padding bytes accordingly when adding extra fields.
=> Fixed delta manifest header alignment

hal/stm32l4.c, options.mk, tools/keytools/Makefile, tools/keytools/sign.c, tools/keytools/sign.py
- Fixes in STM32L4 HAL driver:
- `hal_flash_erase` was using the wrong page index while looping. Changed to page-range to call the HAL_ function once.
- `hal_flash_erase` was calling `hal_flash_unlock()/hal_flash_lock()`, which is not allowed (flash is unlocked at a higher level and could include multiple subsequent operations)
- `hal_flash_write` refactored using the STM32WB as base - which is well tested and guaranteed to work with unaligned data
- New feature in `tools/keytools/sign.py` <- it now tries to read `IMAGE_HEADER_SIZE` from `.config`, if available and set, to override the default (256B). 
Should fix issues in ZD 13566
=> Fixed STM32L4 HAL, added IMAGE_HEADER_SIZE option

.github/workflows/test-renode-multi-mem.yml, .github/workflows/test-renode-multi-sha.yml, options.mk, src/xmalloc.c
Fixed XMALLOC buffers with the following configuration:
`SIGN=ECC384 WOLFBOOT_SMALL_STACK=1 NO_ASM=1`
=> More renode tests + Ecc384 fixes

.github/workflows/test-renode-multi-mem.yml, .github/workflows/test-renode-multi-sha.yml, .github/workflows/test-renode-nrf52.yml, src/image.c, tools/keytools/sign.c, tools/scripts/renode-test-all.sh, tools/test-renode.mk
- Fixed SIGN=NONE option broken since #183 
- Improved renode tests: 
- added SIGN=NONE cases
- removed assembly cases with edwards curves
- added boot time measurement to renode factory test
=> Fixed SIGN=NONE. Improved tests

hal/stm32l4.c
Avoid the override of HAL_GetTick when compiling libwolfboot within the OS/application on STM32L4.
The override is needed to build the minimal flash driver in bootloader context, but must be provided via STM32 CubeMX HAL when building libwolfboot from the application.
See ZD14045.
=> STM32L4: do not override HAL_GetTick when building libwolfboot

tools/delta/Makefile
Fixes a regression that prevents building delta.c symbols in delta update tools (under tools/delta).
Introduced in PR #180 
Discovered by jenkins job `wolfboot-autotest-incremental-update` running on master
=> Fixed build of delta update tools

docs/Signing.md, include/wolfboot/wolfboot.h, tools/keytools/sign.c, tools/keytools/sign.py
sign[.py] allows to specify the partition ID from command line. 
Currently, the firmware update function verifies/updates only the image with ID=1. ID=0 is used for wolfBoot self update.
With the new option `--id N` it's also possible to specify other IDs, from 2 to 15. (Selecting 0 will automatically switch to bootloader self-update)
Signing.md manual updated accordingly, and restructured to cope with increasing amount of options.
=> Support for partition ID in the manifest header

src/libwolfboot.c
Since it is not a static, the compiler may not zero initialize.
ZD 14275
=> Make sure the cipher global is zero initialized

tools/test-expect-version/test-expect-version.c, tools/test.mk
- uniformed tty setup in `test-expect-version` to match `uart-flash-server` settings
- new raspberry-pi device tree changed name of UART0 from `/dev/ttyS0` to `/dev/AMA0`
- don't bail out tests if GPIO direction setting fails (e.g. due to missing GPIO directory / default setup with SPI on)
=> Adjusted automated test after jenkins node update

tools/test.mk
fixed typos in new RSA3072 test names
=> Fixed typo in RSA3072 test name

tools/keytools/sign.py, tools/test-delta.mk
- sign.py : fixed bug in string for the output image path
- test-delta.mk: removed unnecessary reboot actions, causing the tests to occasionally fail
=> Fix errors in delta tests

src/libwolfboot.c
More test application still needing XMEMCPY definitions (not only in TPM mode)
=> Fixed XMEMCPY symbol in test applications

Makefile, docs/encrypted_partitions.md, hal/spi/spi_drv_stm32.c, hal/spi/spi_drv_stm32.h, hal/stm32l0_chacha_ram.ld, include/hal.h, options.mk, src/libwolfboot.c, src/spi_flash.c, src/string.c, src/update_flash.c, test-app/app_stm32l0.c, test-app/led.c, tools/scripts/prepare_encrypted_update.sh
Fixed encrypted self-update (bootloader update).
The combination between `ENCRYPT` and `RAM_CODE` requires some architecture specific changes. This PR introduces a custom linker script for l0 `hal/stm32l0_chacha_ram.ld` that moves the symbols from chacha into RAM. 
A description of the procedure along with instruction to port on other targets is provided in `docs/encrypted_partitions.md`
The self-update procedure has been tested on STM32L0 with external SPI flash, Chacha encryption, and confirmed also to work (via ZD14514).
=> Encrypted self-update

Makefile
`sp_armthumb.c` won't compile with `-O0` optimization without -fomit-frame-pointer (see #241)
=> Add -fomit-frame-pointer to CFLAGS

src/spi_flash.c, src/uart_flash.c, src/update_flash.c
Variable for return value was reused in delta+encrypt, leading to a double write at the wrong offset, causing to store corrupted patch images in the swap partion. 
This is the root cause for the bit flipping in SPI flash memory reported in ZD 15030.
This PR should fix the issue reported and encrypted delta updates should be working again.
=> Fixed bug in encrypted-delta update

src/xmalloc.c
This should fix the failing test in multi-memory configuration
=> Fix ecc_point size for ECC384 with SMALL_STACK/TFM

tools/keytools/keygen.c, tools/keytools/keygen.py, tools/keytools/sign.py
the key_import and keystore_add functions seem to be written when only 2048 size rsa keys were supported since key_import only reads blocks of 2048 size, which will return 0 and write no key for non RSA keys, and keystore_add takes the size of the buffer at face value instead of checking for a valid keysize. this change makes key_import read the keyfile regardless of size and keystore_add check the size of the key buffer and use the real public key size since ecc keys also include the private part of the key after the 2 public parts.
Reproducer:
```
make keytools
tools/keytools/keygen --rsa2048 -g rsa.der
openssl rsa -pubout -inform der -in rsa.der -outform der -out rsaPub.der
tools/keytools/keygen --rsa2048 -i rsaPub.der
```
The result is a `src/keystore.c` that contains a zero sized …
=> fix assumed keysize error

include/wolfboot/wolfboot.h, src/libwolfboot.c, src/update_flash.c, test-app/ARM.ld, test-app/app_nrf52.c
- Using two sectors to keep partition/sector flags
- Keep two redundant set of flags, update one at a time
- Erase is done when the sector is old
- Flags update is faster because Erase is done in advance
- Accessing trailer information (including encryption keys) is done by selecting the newest information
Tested via renode, using nrf52 with NVM_FLASH_WRITEONCE flag on.
=> NVM_FLASH_WRITEONCE refactoring

arch.mk, include/user_settings.h, options.mk
If `__aarch64__` is defined then we know it is a 64-bit ARMv8 and we'll use the SP math from sp_arm64.c with inline assembly. Otherwise we'll use the sp_c32.c small C only version.
=> Support for SP math with AARCH64 when hardware supports it

src/libwolfboot.c
Address of non-selected block to erase was shifted by one block
=> Fix NVM_FLASH_WRITEONCE redundancy

tools/keytools/keygen.c
=> keygen.c: fixed size of exported binary keystore

.github/workflows/test-powerfail-simulator.yml, src/update_flash.c, tools/scripts/sim-update-powerfail-resume.sh
0th sector has been changed with the update partition still being in IMG_STATE_UPDATING state. the state still being IMG_STATE_UPDATING means that a delta update started and that the version may have been switched over, in which case wolfBoot_current_firmware_version() >= wolfBoot_update_firmware_version() no longer tells us if we need to perform an inverse operation on it's own.
also removes part of the update powerfail test that does checks for the previous version without triggering a rollback
=> before calling wolfBoot_delta_update, check if the

README.md, docs/Signing.md, docs/Targets.md, include/loader.h, tools/keytools/keygen.c, tools/keytools/keygen.py
* Update documentation for signing with `--no-sign`, as the key argument should not be supplied.
* Recommend `make keysclean` instead of distclean on keys mismatch.
* Renesas headings/readme link and white-space.
=> Documentation and code comment cleanups

src/update_flash.c, tools/scripts/sim-update-powerfail-resume.sh, tools/test.mk
=> First sector fail fix

test-app/Makefile
=> fix: arch-specific LDFLAGS discarded from test-app

Makefile, docs/Signing.md, src/delta.c, tools/keytools/keygen.c, tools/keytools/sign.c
Use generic buffer API to ensure that the files are open with the right flags.
Non-POSIX systems would require `open()` to use an extra O_BINARY flag to ensure the file is properly processed and sizes calculated accordingly. As file descriptors are only needed in mmap() mode, the win32 interface is reworked to use `fopen()` instead.
Thanks to Erik Chang for reporting this issue.
=> Fixes to sign.c running on windows

stage1/x86_fsp.mk, tools/keytools/sign.c
If the calculated header_sz is smaller than the value requested via .config (or via IMAGE_HEADER_SIZE=x when compiling keytools), override the value calculated with the preset.
=> Override IMAGE_HEADER_SIZE via configuration value

Makefile, cloc_lang_def.txt, hal/x86_fsp_tgl.c, src/boot_x86_fsp.c, src/boot_x86_fsp_payload.c, src/image.c, src/libwolfboot.c, src/loader.c, src/update_disk.c, src/x86/ahci.c, src/x86/ata.c, src/x86/common.c, src/x86/gpt.c, src/x86/hob.c, src/x86/tgl_fsp.c
This PR adds function comments to prep for DO178
=> Document API functions

src/libwolfboot.c
=> handle case where PART_UPDATE_ENDFLAGS % WOLFBOOT_SECTOR_SIZE == 0

docs/Targets.md
=> update docs for the imx-rt1060 config

arch.mk
Upstream mcux-sdk moved some flexcomm files. Fix the locations.
=> Fix LPC MCUX-SDK test

src/image.c, src/libwolfboot.c, tools/keytools/sign.c
Delta updates: patch size was limited to 65535, due to the fields `HDR_IMG_DELTA_SIZE` and `HDR_IMG_DELTA_INVERSE_SIZE` being 2 Bytes long (`uint16_t`).
This PR increases the size for these two fields to four bytes each (`uint32_t`). The maximum patch size for delta updates is now 16MB, due to the position compression in the delta format (24 bit).
=> Delta updates: 32-bit fields for patch size

tools/lms/lms_siglen.sh
Clean up the lms tool `tools/lms/lms_siglen.sh`:
- Pass LMS parms by arg instead of ugly hardcoding into git repo.
- Sanity check LMS parms and give it a print usage.
- Simplify sig len calculation based on reference.
=> tools: clean up lms_siglen.sh.

arch.mk, tools/config.mk, tools/test.mk
Add new `CORTEX_M3` option (default ARCH=ARM is Cortex-M4). The M3 does not support UMAAL.
=> Add new `CORTEX_M3` option (default is M4 with UMAAL)

docs/TPM.md, src/tpm.c, src/update_flash.c, tools/tpm/policy_sign.c
* If using simulator don't extend the unseal PCR to prevent further access. Added `WOLFBOOT_NO_UNSEAL_PCR_EXTEND` option to prevent locking of PCR by random extend.
* Improvements to the `policy_sign` tool (example usage, ecc384 support).
=> TPM sealing cleanups

.github/workflows/test-keytools-msys2.yml, tools/keytools/sign.c, tools/keytools/user_settings.h, tools/test.mk
Added CI for building key tools with MSYS2. Updated wolfSSL submodule to https://github.com/wolfSSL/wolfssl/pull/6881 and adjusted size tests to actual + 32 bytes (extra) rounded to 32-bit.
=> Fixes for building keytools with MSYS2

IDE/Renesas/e2studio/RX72N/Readme.md, IDE/Renesas/e2studio/RX72N/app_RenesasRX01/src/app_RenesasRX01.c, IDE/Renesas/e2studio/RX72N/include/target.h, IDE/Renesas/e2studio/RX72N/resouce/section_info_SWuse.esi, IDE/Renesas/e2studio/RX72N/resouce/section_info_TSIPuse.esi, IDE/Renesas/e2studio/RX72N/x2hex.sh, tools/keytools/keygen.c
Fix compile error due to no __attribute__ support on CCRX
Update Readme
Update application to print a few additional message
Add section files for SW and TSIP use
=> fix and update rx72n port

include/wolfboot/wolfboot.h, src/libwolfboot.c, tools/unit-tests/unit-image.c
zd16115.
On big-endian machines, the type mismatch would always result in the conversion of the lower two bytes.
=> wolfBoot_get_blob_type: fix return type

tools/test.mk, tools/tpm/policy_sign.c
- Updated wolfSSL to 5.6.6: Adjusted footprint test to new binary sizes 
- Updated wolfTPM to latest: Added missing include to tpm policy_sign
=> Submodules update

docs/TPM.md, include/tpm.h, src/tpm.c
Fixes for sealing/unsealing
* Fix for sealing policy, which was not being set on creation.
* Fix to clear the userWithAuth bit requiring policy
* Updated wolfTPM submodule with changes in https://github.com/wolfSSL/wolfTPM/pull/327
* Upstream TigerLake fixes. Adds TPM clear and NV delete.
=> Fixes for sealing/unsealing

IDE/CCS/TMS570LC43xx/README.md, Makefile, arch.mk, stage1/Makefile, test-app/Makefile
Fixes for building TI Hercules
ZD 17394
=> Fixes for building TI Hercules

docs/HAL.md, hal/stm32f7.c, hal/stm32l5.c, hal/stm32u5.c
fork_bootloader() should perform a physical copy of the bootloader to its partition in the second bank only if the content of the two partitions does not already match.
This patch provides a fix for `fork_bootloader()` for the following targets:
- stm32F7
- stm32U5
- stm32L5
Reported in #406
=> DUALBANK: fork_bootloader should only execute once

hal/nxp_t1024.c
Add ability to override macros.
=> Fix for NXP T1024 PHY address mapping

.github/workflows/test-keytools.yml, README.md, docs/Signing.md, docs/firmware_image.md, tools/keytools/sign.c
Added support in `sign.c` for custom TLVs in the manifest header. Numeric values are supported (valid len: 1, 2, 4 or 8). 
[edit: custom length buffers are also supported via `--custom-tlv-buffer`]
The numbers are stored in little-endian format (according to the current format of the other fields). The TLVs are part of the signed image, so their value is secured against modifications.
The custom fields stored in the TLV can be retrieved at runtime in wolfboot by using `wolfBoot_find_header()`.
Documentation is updated accordingly.
=> Added support for custom TLVs in manifest header

docs/Signing.md, docs/firmware_image.md, tools/keytools/sign.c
=> Fix TLV alignment padding and improve documentation

options.mk, tools/keytools/Makefile
Add WOLFSSL_EXPERIMENTAL_SETTINGS to lms/xmss builds to stay in sync with wolfssl master.
The renode lms/xmss tests are using wolfssl master.
=> Fix lms and xmss build.

.github/workflows/test-keytools.yml, docs/Signing.md, tools/keytools/sign.c
Added the ability to create a custom-tlv using an ASCII string to the **keytools/sign tool**.
Example usage:
`sign --custom-tlv-string 0x0030 "0.99.910(6)" --no-sign --sha256 ${projectBaseDir}/release/zephyr.bin 6`
This will create a custom TLV tag as if you'd used --custom-tlv-buffer 0x0030 302E39392E393130283629
Tag: 0030 Len: 11 Val: 302E39392E393130283629 
The above invocation of the sign tool generates the following header in the binary:
Showing that the two commands are equivalent see the following:
Invocation:
`sign --custom-tlv-string 0x0030 "0.99.910(6)" --custom-tlv-buffer 0x0031 302E39392E393130283629 --no-sign --sha256 ${projectBaseDir}/release/zephyr.bin 6`
```
Custom TLVS: 2
TLV 0
----
Tag: 0030 Len: 11 Val: 302E39392E393130283629
-----
TLV 1
----
Tag: 0031 Len: 11 Val: …
```
=> Added support for custom-tlv-string

include/image.h
Possible fix for ZD17804.
User reports that  `r7` is being reused for an intermediate assignment translating a `mov` from memory. Proper clobbering should prevent that from happening.
=> Anti-glitch armor: Added clobbers to assembly

src/libwolfboot.c
Explicit cast to silence warning about negative array index
=> Added explicit cast to silence warning

docs/Targets.md, hal/imx_rt.c
Add support for more flash sizes in the W25QxxxJV series, specifically 2Mbit, 4Mbit, 8Mbit, 32Mbit and 64 Mbit. All the different versions have the same page, sector and block sizes.
=> Add support for more flash sizes in W25QxxxJV series

hal/imx_rt.c
Add support for LPUART4 as debug UART for i.MX RT10xx. Tested on RT1040.
Also fix compile time issue using LPUARTx which is a * by instead using LPUARTx_BASE (https://github.com/wolfSSL/wolfBoot/issues/438).
=> Add support for LPUART4 for i.MX RT10xx

arch.mk, docs/Targets.md, hal/imx_rt.c
Adds support for `MIMXRT1061CVJ5B`. Tested on custom PCB with `MIMXRT1061CVJ5B` and `W25Q128JV` QSPI flash.
=> Add support for MIMXRT1061CVJ5B

CMakeLists.txt, test-app/CMakeLists.txt
Fix for https://github.com/wolfSSL/wolfBoot/issues/426
Add `BUILD_IMAGE` option to CMake to build wolfboot.bin without having to compile test apps
```mkdir build && cd build && cmake -DWOLFBOOT_TARGET=stm32h7 -DWOLFBOOT_PARTITION_BOOT_ADDRESS=0x8020000 -DWOLFBOOT_SECTOR_SIZE=0x20000 -DWOLFBOOT_PARTITION_SIZE=0xD0000 -DWOLFBOOT_PARTITION_UPDATE_ADDRESS=0x80F0000 -DWOLFBOOT_PARTITION_SWAP_ADDRESS=0x81C0000 -DBUILD_IMAGE=yes .. && make```
=> CMake: Add BUILD_IMAGE option

include/otp_keystore.h, include/user_settings.h, options.mk
While testing trustzone + LMS, I've noticed that some objects did not get included properly in the crypto engine, unless they were part of wolfboot authentication via SIGN=.
This should allow to compile PKCS11 engine regardless of the algorithm selected by wolfBoot for the authentication.
=> Fix building PKCS11 TrustZone with any authentication algorithm

src/boot_arm.c
To correctly set up the vector table offset, use the VTOR_NS version before staging a non-secure application or RTOS. This ensures that the interrupts will trigger in the non-secure application.
=> Set VTOR_NS instead of VTOR upon staging when TrustZone is enabled

hal/stm32u5.c, hal/stm32u5.h, include/image.h, src/libwolfboot.c
STM32U5 cache support. Including cache invalidate on `nvm_select_fresh_sector`. 
ZD 18210
=> STM32U5 cache support

Makefile, include/image.h
- ARMORED option is not needed in otp_primer
- do not attempt to compile otp_primer if the option is not declared
=> Fix build OTP options

docs/Signing.md, tools/keytools/keygen.c, tools/keytools/sign.c, tools/keytools/user_settings.h
* Added keygen `--der` option to allow ECC private key as ASN.1/DER. 
* Added sign tool ECC key load support for ASN.1/DER private key (default is raw pub x/y, priv d). 
* Refactored sign tool RSA/ECC logic to consolidate code and allow proper "auto" detection for different RSA key sizes.
* Fix for building key tools with debug and missing `XSNPRINTF`.
=> KeyTool improvements to allow ASN.1/DER private keys with ECC

arch.mk, docs/Targets.md, hal/imx_rt.c, test-app/Makefile, test-app/app_imx_rt.c, test-app/imx_rt_clock_config.c
We've encountered issues where erasing/writing to sectors in flash wasn't visible to the application when reading from flash afterwards. We've narrowed it down to being due to reads happening through the memory mapped flash region, which are cached in the DCache. Reads after erases/writes are therefore at risk of being outdated.
Also, it's stated in NXPs documentation that global interrupts should be disabled when erasing/writing to flash when running with XIP.
See https://wolfssl.zendesk.com/hc/en-us/requests/18238 for more details.
This PR shows the changes needed to fix this, but shouldn't necessarily be merged as-is, as I see you have already added `hal_cache_invalidate`, but it's not implemented for the i.MX platform yet.
=> Fix DCache not being invalidated after erasing/writing to flash on i.MX RT10xx

.github/workflows/test-powerfail-simulator.yml, src/update_flash.c, tools/scripts/sim-delta-wrongversion-update.sh, tools/scripts/sim-update-powerfail-resume.sh, tools/test.mk
=> Bugfix: delta update not rejecting wrong base_version

.github/workflows/test-keytools.yml, .gitignore, Makefile, docs/flash-OTP.md, include/otp_keystore.h, tools/keytools/keygen.c, tools/keytools/otp/Makefile, tools/keytools/otp/otp-keystore-gen.c
Instead of using the `otp-keystore-primer`, an `otp.bin` image can now be generated and flashed separately using the newly introduced `otp-keystore-gen` tool.
=> Add command line tool to generate otp.bin

.github/workflows/test-powerfail-simulator.yml, hal/sim.c, include/wolfboot/wolfboot.h, src/image.c, src/libwolfboot.c, src/update_flash.c, test-app/app_sim.c, tools/scripts/sim-update-emergency-fallback.sh, tools/scripts/sim-update-powerfail-resume.sh, tools/test.mk
the sector flags needing to be reset by update trigger
=> add emergency fallback test, currently fails due to

include/printf.h, src/image.c, src/libwolfboot.c, src/update_flash.c
Proposed additional (optional) logging. 
Add logging for wolfBoot_update() and partition version information. Enabled with `DEBUG_UART` or other PRINTF_ENABLED logging.
@danielinux let me know if you'd like to see this wrapped with another macro like `WOLFBOOT_VERBOSE`?
Example Log:
```
wolfBoot HAL Init
SPI Probe: Manuf 0xC2, Product 0x20
Boot at 0xFFE00000 (size 115856, version 0x2)
Update at 0x200000 (size 115856, version 0x0)
Staring Update (fallback allowed 0)
Update at 0x200000 (size 115856, version 0x0)
Boot at 0xFFE00000 (size 115856, version 0x2)
Versions: Current 0x2, Update 0x3
Copy sector 0 (part 1->2)
Copy sector 0 (part 0->1)
Copy sector 0 (part 2->0)
Boot at 0xFFE00000 (size 115856, version 0x3)
Update at 0x200000 (size 115856, version 0x0)
Copy sector 1 (part 1->2)
Copy …
```
=> Add logging for wolfBoot_update() and partition version information

IDE/Renesas/e2studio/RA6M4/Readme.md, IDE/Renesas/e2studio/RA6M4/Readme_wSCE.md, IDE/Renesas/e2studio/RA6M4/app_RA/src/app_RA.c, IDE/Renesas/e2studio/RX72N/Readme.md, IDE/Renesas/e2studio/RX72N/Readme_withTSIP.md, IDE/Renesas/e2studio/RX72N/app_RenesasRX01/src/app_RenesasRX01.c, docs/Targets.md, src/libwolfboot.c, src/update_flash.c, test-app/app_renesas_rx.c
Fix for update_flash.c `error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]`. Cleanup the swap logic for EXT_ENCRYPTED. Switch to using a uint32_t directly for checking tail magic.
```
src/update_flash.c: In function 'wolfBoot_swap_and_final_erase':
src/update_flash.c:237:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
if (*((uint32_t*)tmpBuffer) == WOLFBOOT_MAGIC_TRAIL) {
^
src/update_flash.c:261:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
*((uint32_t*)tmpBuffer) = WOLFBOOT_MAGIC_TRAIL;
^
cc1.exe: all warnings being treated as errors
```
Cleanup "tail" to "trailer"
=> Fix for error dereferencing type-punned pointer in update_flash.c `wolfBoot_swap_and_final_erase`

hal/renesas-rx.c, hal/renesas-rx.h, include/spi_flash.h, src/boot_renesas.c, src/spi_flash.c
* Fix to make sure wolfBoot leaves IRQ's disabled. The TSIP driver will leave IRQ's on which could cause customer issues. 
* Added new `spi_flash_chip_erase` API for the SPI flash driver. Enabled with `SPI_FLASH_CHIP_ERASE`.
=> Fixes for Renesas RX IRQ on boot and addition of SPI flash full chip erase API

arch.mk, docs/Renesas.md, hal/renesas-rx.c
* Updated Renesas RX TSIP Benchmarks to include RX65N
* Fixed Renesas RX for internal flash write when != 128 bytes. Improved internal flash test case.
* Added hal_led_on/hal_led_off API's enabled with `ENABLE_LED` for testing.
=> Renesas RX fix for flash write and RX65N Benchmarks

arch.mk
After https://github.com/wolfSSL/wolfBoot/pull/475 moved the selection of linker script from `Makefile` to `arch.mk`, building with `TARGET_IMX_HAB=1` only worked when `MCUSDK` wasn't set to 1. This PR fixes this.
cc @danielinux
=> Add HAB support irrespective of MCUSDK setting for imx_rt target

hal/aurix_tc3xx.c
Fixes typo in variable name that causes a compile error. 
Error was introduced during code review when splitting up combined assignment/declarations, and not found since CI doesn't compile `hal/aurix_tc3xx.c`.
Confirmed the fix builds and runs as expected on tc3xx.
=> Fix AURIX build error 

tools/keytools/Makefile, tools/keytools/keygen.c
when WOLFBOOT_UNIVERSAL_KEYSTORE=1, the keystore.der file should align all the keys to the maximum slot size (576).
=> Keygen to allow multiple keystore types

IDE/AURIX/test-app/Lcf_Gnuc_Tricore_Tc.lsl, IDE/AURIX/wolfBoot-tc3xx/Lcf_Gnuc_Tricore_Tc.lsl
Fixes issue with the latest version of AURIX iLLD SDK, where UCB BMHD entry objects are added to what was a previously unused output linker section, resulting in a non-contiguous image and very large output binary.
The discarded input sections should not have been in the output image in the first place, though they were unused with GCC builds using older iLLD versions so posed no problems.
=> tc3xx: remove bmhd input sections from linker script

docs/Targets.md
Adds a blurb about AURIX TC3xx support to Targets.md, pointing interested users to the documentation and mentioning wolfHSM
Also re-alphabetizes the table of contents at the top of Targets.md and fixes a broken link
=> doc update: add AURIX TC3xx to Targets.md

tools/test-renode.mk
SIGN_ARGS is getting duplicate args.
```
$./silly_reproducer 
Building key tools
make[1]: Entering directory '/home/jordan/work/boot/src/tools/keytools'
Building signing tool
Building keygen tool
make[1]: Leaving directory '/home/jordan/work/boot/src/tools/keytools'
/home/jordan/work/boot/src/tools/keytools/sign --ml_dsa --sha256 --ml_dsa --sha256  \
```
```
$cat silly_reproducer 
#!/bin/bash
cp config/examples/sim-ml-dsa.config .config || exit 1
make distclean && make clean
make keytools || exit 1
make test-sim-internal-flash-with-update V=1 2>&1 | grep "sign.*sha256.*sha256"
```
=> tools renode: reset SIGN_ARGS.

src/libwolfboot.c
ZD 19133
I found a mistake in the update trigger code where the selSec for nvm writeonce was being subtracted from the base address and then subtracted again for the erase operation. We need to add a test with a fullsize update image that would have been corrupted by this mistake. I've previously tried and failed to make a full size image test in test.mk @danielinux I could use advise or help on this
=> stop the selSec from being applied twice to lastSector

tools/keytools/sign.c
This PR addresses the enhancement suggested in #527.
=> Sign tool: use manifest header to retrieve base version

.github/workflows/test-renode-nrf52.yml, docs/PQ.md, docs/Targets.md, include/image.h, options.mk, tools/scripts/renode-test-update.sh, tools/test-renode.mk, tools/test.mk
Prune external post-quantum integrations: ext_LMS, ext_XMSS.
- Removed `WOLFBOOT_SIGN_ext_LMS`, `WOLFBOOT_SIGN_ext_XMSS` from`include/image.h`. 
- Removed `ext_LMS`, `ext_XMSS` from `options.mk`.
- Removed ext_LMS, ext_XMSS tests from `.github/workflows/`.
- Removed ext_LMS, ext_XMSS from `tools/` build scripts.
- Updated `docs/PQ.md`, and removed references to the external integrations.
- Spelling cleanup in `docs/Targets.md`.
=> Remove external ext_lms, ext_xmss pq integrations.

hal/zynq.h
Fixes possible redefinition of macros like `EL2_HYPERVISOR` when building in Vitis. Occurs when `USE_BUILTIN_STARTUP` is defined and the Vitis boot.S is used.
ZD 18796
=> ZynqMp - avoid redefinition when using USE_BUILTIN_STARTUP.

IDE/AURIX/test-app-wolfHSM/.cproject, IDE/AURIX/test-app/.cproject, IDE/AURIX/test-app/.settings/language.settings.xml, IDE/AURIX/wolfBoot-tc3xx-wolfHSM/.cproject, IDE/AURIX/wolfBoot-tc3xx/.cproject, IDE/AURIX/wolfBoot-tc3xx/.settings/language.settings.xml, tools/scripts/tc3xx/wbaurixtool.sh
- Fixes build errors introduced by new version of AURIX dev studio (1.10.6)
- Fixes to AURIX helper script to properly generate macros for non-wolfHSM builds, with corresponding updates to non-HSM AURIX project
=> TC3xx: Fixes for ADS 1.10.6

hal/imx_rt.c
`sysPllConfig_BOARD_BootClockRUN`, `usb1PllConfig_BOARD_BootClockRUN` and `videoPllConfig_BOARD_BootClockRUN` are unused, and were causing `multiple definition` errors when compiling the wolfBoot library into our application as the board code generated by MCUXpresso Config Tools also contains definitions for these variables.
=> Remove unused variables in imx_rt.c causing `multiple definition` errors

IDE/IAR/README.md, IDE/IAR/sign_test_app.bat, include/image.h, src/update_flash.c, tools/test-renode.mk, tools/test.mk
Add support for Armored mode with IAR. Currently only supports ECDSA and Cortex-M. ZD19190
=> Add support for Armored mode with IAR

hal/aurix_tc3xx.c
Quick fix to the tc3xx HAL to properly handle flash writes across sector boundaries. 
Note: **This is not necessary for current usage, but will be necessary for ELF loading.** 
Splitting this fix into is own PR so @billphipps can use it for some of his unrelated feature work.
=> tc3xx HAL write fix

arch.mk
As reported in ZD 20152, this flag is needed to prevent unaligned access when running integrity check.
=> Fixed unaligned access report by user (Cortex-A5)

src/pkcs11_store.c, tools/unit-tests/unit-pkcs11_store.c
`wolfPKCS11_Store_Remove` was added in wolfPKCS11 2.0, support for it is needed.
=> wolfPKCS 2.0 support

.github/workflows/build-keytools-windows.yml, .github/workflows/footprint.yml, .github/workflows/test-build-aarch64.yml, .github/workflows/test-build-cmake.yml, .github/workflows/test-build-kontron-vx3060-s2.yml, .github/workflows/test-build-lms.yml, .github/workflows/test-build-mcux-sdk.yml, .github/workflows/test-build-pico-sdk.yml, .github/workflows/test-build-sim-tpm.yml, .github/workflows/test-build.yml, .github/workflows/test-cppcheck.yml, .github/workflows/test-custom-tlv-simulator.yml, .github/workflows/test-elf-scattered.yml, .github/workflows/test-external-library-paths.yml, .github/workflows/test-keytools-msys2.yml, .github/workflows/test-keytools.yml, .github/workflows/test-library.yml, .github/workflows/test-parse-tools.yml, .github/workflows/test-powerfail-simulator.yml, .github/workflows/test-renode-fastmath.yml, .github/workflows/test-renode-noasm-smallstack.yml, .github/workflows/test-renode-noasm.yml, .github/workflows/test-renode-nrf52.yml, .github/workflows/test-renode-sha3.yml, .github/workflows/test-renode-sha384.yml, .github/workflows/test-renode-smallstack.yml, .github/workflows/test-sunnyday-simulator.yml, .github/workflows/test-units.yml, .github/workflows/test-wolfhsm-simulator.yml, .github/workflows/test-x86-fsp-qemu.yml
Ensures workflow tests abort early when stuck.
On two of my recent pull requests, the workflow got stuck here:
```
Run sudo apt-get install -y gcc-arm-none-eabi
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
binutils-arm-none-eabi libnewlib-arm-none-eabi libnewlib-dev
libstdc++-arm-none-eabi-dev libstdc++-arm-none-eabi-newlib
Suggested packages:
libnewlib-doc
The following NEW packages will be installed:
binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi
libnewlib-dev libstdc++-arm-none-eabi-dev libstdc++-arm-none-eabi-newlib
0 upgraded, 6 newly installed, 0 to remove and 21 not upgraded.
Need to get 574 MB of archives.
After this operation, 3106 MB of additional disk space will be used. …
```
=> Reduce workflow timeout from default 360 minutes to 15
