wolfSSL/wolfBoot

- arch.mk
- docs/Targets.md
- hal/stm32g0.c
- hal/stm32g0.ld
- src/libwolfboot.c
- test-app/Makefile
- test-app/app_samr21.c
- test-app/app_stm32g0.c
- test-app/led.c
Support for STM32-G0 @64MHz
- hal fully tested (including update)
- flash requires NVM_FLASH_WRITEONCE
to review/merge after STM32L0 PR
> Added support for STM32-G0

- docs/Targets.md
- hal/stm32wb.c
- hal/stm32wb.ld
- test-app/app_stm32wb.c
- test-app/led.c
Added HAL + simplest test application for STM32WB55
> Added support for STM32WB

- hal/spi/spi_drv_stm32.c
- tools/test-expect-version/test-expect-version.c
- tools/test.mk
Updated CI testbed: now using SPI for external flash and TPM.
- Added CI test cases with RSA based signature
- Added CI test cases with ECC256 verified using TPM.
- Minor fix in SPI driver
> Added test cases for RSA and TPM

- README.md
We support multiple Cortex architectures and are continually expanding.
> Remove obsolete section in README.md

- hal/stm32wb.c
Important bug fixes for STM32WB device driver.
> Stm32wb hal fixes

- src/image.c
- tools/keytools/sign.c
RSA with an ASN.1 header is a standard signature header added to openssl signatures and is used with TLS. This fix tests the length, and if its larger than the hash expected, extracts the hash from the ASN.1 encoded signature.
On by default, can be disabled using `NO_RSA_SIG_ENCODING`.
Added support for signing with encoding using `--rsa2048enc` or `--rsa4096enc`.
ZD 10489
> Add support for using an RSA signature that includes ASN.1 encoded header

- hal/lpc.c
> LPC: Fix aligned page address write

- src/libwolfboot.c
- prevent dereferencing unaligned fields in the manifest headers (ZD10590)
- check return value of `wolfBoot_find_header`
> Sanity check for aligned fields in manifest header

- src/spi_flash.c
ZD 10751 - fix needed for bootloader update
> Added RAMFUNCTION to spi_wait_busy

- .gitignore
- src/libwolfboot.c
- tools/unit-tests/Makefile
- tools/unit-tests/README.md
- tools/unit-tests/unit-parser.c
Improved logic for boundary checks on manifest header fields (ZD10589)
> Fixed manifest header boundary checks

- README.md
- Updated submodules
- Added changelog
> Prepare release 1.6

- docs/firmware_image.md
Thanks to @DurandA - reported via #82
> Updated documentation to reflect latest design

- hal/stm32h7.c
- STM32H7XX driver hal_flash_write() fixed: according to RM0433 only 256bit writes (32B) can be written at one time.
- Added `hal_flash_dualbank_swap` function to enable DUALBANK_SWAP on this platform
> Fixed hal_flash_write in stm32h7, added dualbank option

- src/image.c
> Fixed check on FW image size in wolfBoot_open_image

- Makefile
- include/user_settings.h
- options.mk
Updating the wolfTPM submodule to latest master and enabling WOLFTPM_USER_SETTINGS.
**this should be tested well before merging** due to the major version change v1.9->v2.0
> Add latest wolftpm

- tools/test-enc.mk
(minor change) - Updated test-enc.mk to run on a Jenkins node with STM32WB55
> Updated test with encryption+uart to run on Jenkins

- docs/Targets.md
As reported in #105 - Updated documentation for RaspberryPi
> Fixed RaspberryPi documentation (dtb is not signed)

- hal/stm32h7.c
As mentioned  in #109:
- Offset for the write operations was off by one place
- Loop in `flash_program_on` was checking the wrong flag
> Correct BANK2 offset in STM32H7. Fixed flag to check on flash write

- tools/test.mk
Minor fix in tools/test.mk (should fix a regression in test-34-self-update)
> Fixed self-update test

- docs/API.md
wolfBoot_update -> wolfBoot_update_trigger (see issue #136)
> Fixed API function name in docs

- docs/Targets.md
> STM32L5 Documentation improvements

- README.md
> [README.md] Fix wolfBoot_update_trigger() function name

- IDE/IAR/README.md
- IDE/IAR/target.h
- IDE/IAR/wolfboot-test-app.ewp
- IDE/IAR/wolfboot.ewp
> Update filenames in IAR IDE project.

- README.md
- src/xmalloc.c
* Update wolfTPM and wolfSSL submodules
* Fixes related to submodule updates
* Update release notes
> Release v1.9 updates

- src/delta.c
- tools/delta/bmdiff.c
> Fixed corner case delta bug when matching across old/new sector

- docs/Targets.md
For use of the official STM32 tools.
> Improve STM32 G0 documentation

- .gitignore
- IDE/IAR/wolfboot.ewp
- hal/stm32f4.c
> Minor fixes to get the IAR example building

- docs/Targets.md
- hal/stm32h7.c
- test-app/app_stm32h7.c
> Cleanup STM32H7 target documentation and code

- .github/workflows/test-renode-nrf52.yml
- .gitignore
- Makefile
- include/loader.h
- include/user_settings.h
- include/wolfboot/wolfboot.h
- options.mk
- src/image.c
- src/xmalloc.c
- tools/keytools/keygen.c
- tools/keytools/keygen.py
- tools/keytools/sign.c
- tools/keytools/sign.py
- tools/keytools/user_settings.h
- tools/test-renode.mk
> New signature algorithm: ECC384

- src/image.c
- tools/test.mk
- Fixed compile errors in wolfTPM integration introduced in #183 
- Fixed test-expect-version invocation from test.mk
> Fix regressions in wolfTPM integration and tests

- docs/Targets.md
- src/boot_aarch64.c
Note: There is not output after running the QEMU step. Investigating...
> Updates to documentation for using wolfBoot on Raspberry Pi and QEMU

- IDE/IAR/sign_test_app.bat
Broken with the key store PR #212 and wasn't properly fixed in PR #230.
ZD 14647
> Fix the IAR sign script

- hal/zynq.c
Changes made for customer that Jeff did not upstream.
> Fixes for wolfBoot Xilinx QSPI support

- include/user_settings.h
- options.mk
- src/xmalloc.c
- tools/test.mk
The usual housekeeping on memory allocations and footprint size to keep in sync with submodules.
> Updated wolfSSL and wolfTPM submodules

- arch.mk
- hal/spi/spi_drv_stm32.c
- hal/spi/spi_drv_stm32.h
- include/spi_drv.h
> Experimental STM32U5 external flash support

- .github/workflows/footprint.yml
- .github/workflows/test-renode-multi-mem.yml
- .github/workflows/test-renode-multi-sha.yml
- .github/workflows/test-renode-nrf52.yml
- tools/renode/Dockerfile
- tools/renode/docker-test.sh
- tools/scripts/renode-test-update.sh
Moved most of the commands inside the renode container.
Updated docker image to compile and run all tools, wolfboot and test image within the renode container.
> Github workflows: new test scripts

- hal/stm32f4.c
- src/image.c
- tools/test.mk
Broken in PR #242: https://github.com/wolfSSL/wolfBoot/pull/242/commits/cd6597e2a07af6c35b0d156611d4a26ea90bbdea
> Fix for external SPI test on F4

- include/image.h
- src/libwolfboot.c
- tools/test-delta.mk
- tools/test-enc.mk
- tools/uart-flash-server/Makefile
- tools/uart-flash-server/ufserver.c
* Fixes for encrypt/decrypt with unaligned address.
* Fix issue with reading byte count on a file using Mac OS.
* Cleanups for uart-flash-server.
Fixes #253
> Fixes for encrypt/decrypt with unaligned address

- .github/workflows/test-build.yml
- .github/workflows/test-configs.yml
- hal/spi/spi_drv_stm32.c
- include/spi_drv.h
- test-app/app_stm32l0.c
Also adds GitHub Actions to test builds for all ARM based example configs.
Tested with:
```
cp ./config/examples/stm32wb-tpm.config .config
make clean
make
```
> Fix for wolfBoot with wolfTPM

- hal/spi/spi_drv_stm32.c
- hal/spi/spi_drv_stm32.h
- hal/stm32f4.c
that were introduced in #264 / #265
> Fixed regressions on TPM SPI communication

- CMakeLists.txt
- cmake/wolfboot.cmake
- docs/Targets.md
- hal/stm32h7.ld
- test-app/ARM-stm32h7.ld
Changes that I made to get wolfBoot building reliably with `PULL_LINKER_DEFINES`.
> Improvements and fixes for CMake

- .github/workflows/test-units.yml
- include/encrypt.h
- include/image.h
- src/libwolfboot.c
- tools/unit-tests/Makefile
- tools/unit-tests/target.h
- tools/unit-tests/unit-extflash.c
- tools/unit-tests/unit-parser.c
- Added unit tests for encrypt/decrypt functions with EXT_ENCRYPTED + EXT_FLASH
- Fixed two issues detected
> Encryption unit tests

- src/libwolfboot.c
> Fix bug in get_trailer_at()

- tools/test.mk
> Removed duplicate test entry in test.mk

- docs/PubkeySealing.md
- src/image.c
- tools/preseal/Makefile
- tools/preseal/preseal.c
fix a key not being unloaded, normaly doesn't crop up since in normal circumstances wolfBoot and the TPM both turn on fresh but on the simulator not freeing the key caseus a leak
> add ability to compile preseal with no filesystem

- README.md
> Fixed typo in wolfBoot 1.16 changelog

- hal/stm32l4.c
This patch sets the STM32L4 clock speed to 80MHz as discussed over email with David Garske.
> STM32L4: set clock speed to 80MHz

- Makefile
- docs/Signing.md
- docs/Targets.md
- docs/encrypted_partitions.md
- docs/firmware_update.md
- docs/keystore.md
- tools/keytools/keygen.py
- tools/keytools/sign.py
> Deprecate python keytools.

- src/libwolfboot.c
> fix bad address copy if base is not the same as addr_read

- tools/keytools/sign.c
Support use case where an LMS public key only is imported, without keygen.
> Support LMS with pub key only.

- .github/workflows/test-tpm.yml
- src/tpm.c
> Fix for ROT with no auth

- src/tpm.c
Resolves issue with trying to use the existing session multiple times. The TPM nonce was being lost.
Fix to use the new unset auth session API, that captures the last TPM nonce, so the session auth can be properly set again. 
Requires wolfTPM PR https://github.com/wolfSSL/wolfTPM/pull/299
> Fix for setting and unsetting the session auth

- tools/keytools/keygen.c
- tools/keytools/user_settings.h
> Fixed keygen ecc key initialization

- hal/nxp_t1024.c
Fix for NXP T1024 to get MAC address from Integrity OS ethernet configuration area in flash.
> Fix for NXP T1024 to get MAC address from Integrity OS ethernet config

- hal/same51.c
Increment the address when erasing multiple pages.
> SAM E51: hal_flash_erase bugfix

- .github/workflows/test-custom-tlv-simulator.yml
- Makefile
- docs/firmware_image.md
- include/image.h
- include/wolfboot/wolfboot.h
- test-app/app_sim.c
- tools/keytools/sign.c
> Custom TLV: enforce 8B alignment for all fields

- test-app/ARM.ld
Fixes a linker error in the STM32F4 test-app
> Added section for ARM.exidx in test-app linker script

- hal/stm32u5.c
> STM32U5: Only try and invalidate cache if enabled

- docs/Signing.md
- docs/azure_keyvault.md
Thanks to @jachin84 for reporting #462 and providing the correct sequence.
> Added documentation for signing with Azure Key Vault

- hal/imx_rt.c
Follow up fixes from debugging #495 on 1064. Fixes issue where wrong FlexSPI index for 1064 was used in ROM API
> Fix ROM API hang for imx rt1064

- .github/workflows/test-renode-fastmath-smallstack.yml
- .github/workflows/test-renode-noasm-smallstack.yml
- .github/workflows/test-renode-noasm.yml
- .github/workflows/test-renode-nrf52.yml
- .github/workflows/test-renode-sha3.yml
- .github/workflows/test-renode-sha384.yml
- .github/workflows/test-renode-smallstack.yml
- include/user_settings.h
In `include/user_settings.h`, define NO_ASN if NO_RSA defined.
> user_settings: default to NO_ASN if NO_RSA defined.
